### ISSUE TITLE
Represent Asn_core.asn as a partial fold

### ISSUE THREAD

**Issue by marklrh** [mirleft/ocaml-asn1-combinators#12]
Hi, @pqwy 

I saw the comment you left in [asn_cache.ml](https://github.com/mirleft/ocaml-asn1-combinators/blob/master/src/asn_cache.ml#L4). Would you like to explain to me further about your comment? I am facing similar problems and I really would not like to do such hack to memorize HOAS-style expression.

**Comment by pqwy** [comment]
Sure. Write me an email or meet me back in the lab when I come to Cambridge.
