### ISSUE TITLE
Asn_time

### ISSUE THREAD

**Issue by hannesm** [mirleft/ocaml-asn1-combinators#17]
could just borrow the representation from Ptime, this would be brilliant (namely `int * int64` -- the days since UNIX epoch * picoseconds of the current day).. this would make it a bit more uniform and enable us to use the Ptime conversions, plus being able to get rid of the asn_time code here AFAICS

thx!

**Comment by pqwy** [comment]
Yes, I *know* there is a home-grown time in there, for god's sake. What I just pushed out is only the smallest, compatible, batch of changes that I accumulated over the past two years.

**Comment by hannesm** [comment]
thanks for pushing this through... the other two things which would be great to have here are: get the byte array of a subelement (to get rid of this hack https://github.com/mirleft/ocaml-x509/blob/57ff8ddcacb710f705d22e4e19f6bf2e758f160d/lib/x509_certificate.ml#L174) and (or?) retain the string encoding down (esp. for some CAs which require countryName to be ASCII, not UTF8 encoded https://github.com/mirleft/ocaml-x509/issues/69) -- if the latter is done, it is likely that the former doesn't need any work, but we can re-encode the bytes from the decoded structure.

**Comment by hannesm** [comment]
thanks for making the 0.2.0 release which fixes this issue
