### ISSUE TITLE
implicitly tagged choice within implicit tagged X needs to be explicitly tagged

### ISSUE THREAD

**Issue by hannesm** [mirleft/ocaml-asn1-combinators#18]
When I started implementing certificate revocation lists, I [first implemented](https://github.com/hannesm/ocaml-x509/commit/66c3ae2be4fefaaf66c3e3dc2719e0455e5c924a) the `CRL Distribution Points` extension in X.509v3, with the following grammar snippet (all within an `implicitly tagged module`):

```
   CRLDistributionPoints ::= SEQUENCE SIZE (1..MAX) OF DistributionPoint

   DistributionPoint ::= SEQUENCE {
        distributionPoint       [0]     DistributionPointName OPTIONAL,
        reasons                 [1]     ReasonFlags OPTIONAL,
        cRLIssuer               [2]     GeneralNames OPTIONAL }

   DistributionPointName ::= CHOICE {
        fullName                [0]     GeneralNames,
        nameRelativeToCRLIssuer [1]     RelativeDistinguishedName }
```

The piece of interest here is the `distributionPoint` (being optional and implicitly tagged within a sequence), pointing to an `implicitly tagged choice`, which in the `GeneralNames` case leads to a (sequence of) choice.   Now, the first attempts at writing parsers failed:

```OCaml
  let distribution_point_name =
    map (function | `C1 s -> `Full s | `C2 s -> `Relative s)
        (function | `Full s -> `C1 s | `Relative s -> `C2 s)
    @@
    choice2
      (implicit 0 gen_names)
      (implicit 1 Name.name)

  let distribution_point =
    sequence3
      (optional ~label:"distributionPoint" @@ implicit 0 distribution_point_name)
      (optional ~label:"reasons"           @@ implicit 1 reason)
      (optional ~label:"cRLIssuer"         @@ implicit 2 Name.name)

  let crl_distribution_points = sequence_of distribution_point
```

I tried to manually figure out from an example what is wrong (using the [very useful ASN.1 JS decoder](https://lapo.it/asn1js/)) -- and it turns out that the hex dump for a single distribution point is e.g. `30 2D  A0 2B A0 29 86 27`, so a sequence `30` followed by `A0`, and `A0` again.  Replacing the `implicit` with an `explicit` above in `(optional ~label:"distributionPoint" @@ *implicit* 0 distribution_point_name)` did the trick, I can now parse the CRL distribution point extension (of all certificates of my trust anchor set shipped with my operating system, ~30 certificates which contain this extension).  I couldn't believe the spec is wrong (and furthermore, to have a single explicitly tagged element in a sequence or choice (see the example below) doesn't make much sense, when all other elements are implicitly tagged.

Digging deeper, I wanted to understand the discrepancy between the specification and the code (esp since there is a comment in the `General_name.general_name` code as follows:
```
        (* Everybody uses this as explicit, contrary to x509 (?) *)
        (explicit 4 Name.name)
```

And various others, like this [piece of python](https://github.com/wbond/asn1crypto/blob/master/asn1crypto/x509.py#L1349) do it the same.  But e.g. the [erlang OTP](https://github.com/erlang/otp/blob/master/lib/asn1/test/asn1_SUITE_data/PKIX1Implicit93.asn1#L247) parses the ASN grammars directly, without any `implicit` to `explicit` conversion (from early [release notes](http://erlang.org/documentation/doc-5.1/lib/asn1-1.3.2/notes_history.html), it seems they had the same issue: `The compiler did not accept CHOICE types as components of a SEQUENCE or SET when the modules tag default was IMPLICIT.`).

Searching a bit further on the internet leads to various medium quality results, but in the end I found [this very helpful comment](https://security.stackexchange.com/questions/11617/question-about-implicitly-tags-in-asn-1) which refers to the ASN spec:

```
The tagging construction specifies explicit tagging if any of the following holds:
...
c) the "Tag Type" alternative is used and the value of "TagDefault" for the module is "IMPLICIT TAGS" or "AUTOMATIC TAGS", but the type defined by "Type" is a choice type, open type, or a "DummyReference" (see ITU-T Rec. X.683 | ISO/IEC 8824-4).
```

This seems to be a legitimate rule (and is _not_ specified in the DER/BER encoding rules, since it is general to ASN.1, and not specific to a concrete encoding).  Intuitively, it makes sense since you can't implicitly tag sth which does not have a binary representation (the choice), thus to not loose the tag information, you need to make it explicit.  It also seems to be a common mistake, [RSA BSAFE](https://community.rsa.com/docs/DOC-47900) also suffered from this issue.

**Comment by pqwy** [comment]
Ah, no, it does tell:

> The IMPLICIT alternative shall not be used if the type defined by "Type" is an untagged choice type or an untagged open type or an untagged "DummyReference".

It asks to reject such grammars. We'll do the nice thing instead.
