### ISSUE TITLE
Bigarray and cstruct >= 5.0.0

### ISSUE THREAD

**Issue by NathanReb** [mirleft/ocaml-asn1-combinators#28]
`cstruct 5.0.0` appears to have dropped its dependency over `bigarray` which causes linking issues with `asn1-combinators` as it was transitively depending on it.

#27 fixes it for future versions but it might be worth updating a few `opam` files on `opam-repository` by adding an upper bound to the `cstruct` dependency.

I'm happy to help with that if you don't have time to take care of it so let me know what you think!

**Comment by XVilka** [comment]
Are there any updates on this?

**Comment by hannesm** [comment]
thanks for the report.

https://github.com/ocaml/opam-repository/pull/15199 added a patch for asn1-combinators 0.2.0; #27 is now merged as #31.
